#
# This is still experimental docker-compose configuration.
# Rationale behind some of the options used:
#
# 1) 'stdin_open: true' and 'tty: true' together with `CMD bash` in Dockerfiles
# are used to prevent container from early exit to be able to run `docker
# attach <container-name>` instead of `docker exec -it <container-name> bash`.
#
# 2) Using '/dev/log' volume is useful for containers' logging on the host
# machine.
#
# 3) Using '/share' volume is used to keep development .deb packages there.
# They are installed from containers (see containers' APT configuration in
# '/etc/apt/sources.list.d/*).
#
# 4) 'depends_on' is used to prevent running e.g. 'lizardfs-client' before
# 'lizardfs-master' starts.
#
# 5) Some of the following options are needed to e.g. run strace/ltrace within
# container: 'privileged', 'cap_add', 'security_opt' (particularly SYS_PTRACE).
#

version: '3'
services:
  ###########################
  # Master
  ###########################
  lizardfs-master:
    container_name: "lizardfs-master"
    hostname: lizardfs-master
    build: ./lizardfs-master
    #image: lizardfs/master
    stdin_open: true
    tty: true
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.2"
    extra_hosts:
      - "mfsmaster:127.0.0.1"
    # Volumes needed for logging
    # See: https://www.projectatomic.io/blog/2016/10/playing-with-docker-logging/
    volumes:
      - /dev/log:/dev/log
      - /share:/share
    # TODO seems to work without it - why?
    ports:
      - "9425:9425"

  ###########################
  # Shadow #1
  ###########################
  lizardfs-shadow-01:
    container_name: "lizardfs-shadow-01"
    hostname: lizardfs-shadow-01
    build: ./lizardfs-shadow
    #image: lizardfs/shadow
    stdin_open: true
    tty: true
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.3"
    extra_hosts:
      - "mfsmaster:172.31.0.2"
    volumes:
      - /dev/log:/dev/log
      - /share:/share

  ###########################
  # Shadow #2
  ###########################
  lizardfs-shadow-02:
    container_name: "lizardfs-shadow-02"
    hostname: lizardfs-shadow-02
    build: ./lizardfs-shadow
    #image: lizardfs/shadow
    stdin_open: true
    tty: true
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.4"
    extra_hosts:
      - "mfsmaster:172.31.0.2"
    volumes:
      - /dev/log:/dev/log
      - /share:/share

  ###########################
  # Shadow #3
  ###########################
  lizardfs-shadow-03:
    container_name: "lizardfs-shadow-03"
    hostname: lizardfs-shadow-03
    build: ./lizardfs-shadow
    #image: lizardfs/shadow
    stdin_open: true
    tty: true
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.5"
    extra_hosts:
      - "mfsmaster:172.31.0.2"
    volumes:
      - /dev/log:/dev/log
      - /share:/share

  ###########################
  # Client
  ###########################
  lizardfs-client:
    container_name: "lizardfs-client"
    hostname: lizardfs-client
    build: ./lizardfs-client
    #image: lizardfs/client
    stdin_open: true
    tty: true
    depends_on:
      - lizardfs-master
    # Give extended privileges to this container TODO needed?
    privileged: true
    #cap_add:
    #  - SYS_ADMIN
    #devices:
    #  - /dev/fuse:/dev/fuse
    #security_opt:
    #  - apparmor:unconfined
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.10"
    extra_hosts:
      - "mfsmaster:172.31.0.2"
    volumes:
      - /dev/log:/dev/log
      - /share:/share

  ###########################
  # Chunkserver #1
  ###########################
  lizardfs-chunkserver-01:
    container_name: "lizardfs-chunkserver-01"
    hostname: lizardfs-chunkserver-01
    build: ./lizardfs-chunkserver
    #image: lizardfs/chunkserver
    stdin_open: true
    tty: true
    depends_on:
      - lizardfs-master
    # Uncomment to be privileged to run e.g. strace or ltrace
    # See: https://github.com/moby/moby/issues/21051#issuecomment-325036902
    #cap_add:
    #  - SYS_ADMIN
    #  - SYS_PTRACE
    #privileged: true
    #security_opt:
    #  - apparmor:unconfined
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.21"
    extra_hosts:
      - "mfsmaster:172.31.0.2"
    volumes:
      - /dev/log:/dev/log
      - /share:/share
    # - ./data/cs1_hdd0:/mnt/hdd0
    #environment:
    #  - LABELS=M
    #  - SIZE=10

  ###########################
  # Chunkserver #2
  ###########################
  lizardfs-chunkserver-02:
    container_name: "lizardfs-chunkserver-02"
    hostname: lizardfs-chunkserver-02
    build: ./lizardfs-chunkserver
    #image: lizardfs/chunkserver
    stdin_open: true
    tty: true
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.22"
    extra_hosts:
      - "mfsmaster:172.31.0.2"
    volumes:
      - /dev/log:/dev/log
      - /share:/share
    # - ./data/cs2_hdd0:/mnt/hdd0
    #environment:
    #  - LABELS=MB
    #  - SIZE=10

  ###########################
  # Chunkserver #3
  ###########################
  lizardfs-chunkserver-03:
    container_name: "lizardfs-chunkserver-03"
    hostname: lizardfs-chunkserver-03
    build: ./lizardfs-chunkserver
    #image: lizardfs/chunkserver
    stdin_open: true
    tty: true
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.31.0.23"
    extra_hosts:
      - "mfsmaster:172.31.0.2"
    volumes:
      - /dev/log:/dev/log
      - /share:/share
    # - ./data/cs3_hdd0:/mnt/hdd0
    #environment:
    #  - LABELS=MB
    #  - SIZE=10

###########################
# Network config
###########################
networks:
  lizardfs-net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.31.0.0/16
