version: '3'
services:
  ###########################
  # Master
  ###########################
  lizardfs-master:
    container_name: "lizardfs-master"
    hostname: lizardfs-master
    build: ./lizardfs-master
    #image: lizardfs/master
    networks:
      lizardfs-net:
        ipv4_address: "172.20.0.2"
    extra_hosts:
      - "mfsmaster:127.0.0.1"
    # Volumes needed for logging
    # See: https://www.projectatomic.io/blog/2016/10/playing-with-docker-logging/
    volumes:
      - /dev/log:/dev/log
    # TODO seems to work without it - why?
    #ports:
    #  - "9425:9425"

  ###########################
  # Shadow
  ###########################
  lizardfs-shadow:
    container_name: "lizardfs-shadow"
    hostname: lizardfs-shadow
    build: ./lizardfs-shadow
    #image: lizardfs/shadow
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.20.0.3"
    extra_hosts:
      - "mfsmaster:172.20.0.2"
    volumes:
      - /dev/log:/dev/log

  ###########################
  # Client
  ###########################
  lizardfs-client:
    container_name: "lizardfs-client"
    hostname: lizardfs-client
    build: ./lizardfs-client
    #image: lizardfs/client
    depends_on:
      - lizardfs-master
    # Give extended privileges to this container TODO needed?
    privileged: true
    #cap_add:
    #  - SYS_ADMIN
    #devices:
    #  - /dev/fuse:/dev/fuse
    #security_opt:
    #  - apparmor:unconfined
    stdin_open: true
    tty: true
    networks:
      lizardfs-net:
        ipv4_address: "172.20.0.5"
    extra_hosts:
      - "mfsmaster:172.20.0.2"
    volumes:
      - /dev/log:/dev/log

  ###########################
  # Chunkserver #1
  ###########################
  lizardfs-chunkserver-01:
    container_name: "lizardfs-chunkserver-01"
    hostname: lizardfs-chunkserver-01
    build: ./lizardfs-chunkserver
    #image: lizardfs/chunkserver
    depends_on:
      - lizardfs-master
    # Uncomment to be privileged to run e.g. strace or ltrace
    # See: https://github.com/moby/moby/issues/21051#issuecomment-325036902
    #cap_add:
    #  - SYS_ADMIN
    #  - SYS_PTRACE
    #privileged: true
    #security_opt:
    #  - apparmor:unconfined
    networks:
      lizardfs-net:
        ipv4_address: "172.20.0.11"
    extra_hosts:
      - "mfsmaster:172.20.0.2"
    volumes:
      - /dev/log:/dev/log
    # - ./data/cs1_hdd0:/mnt/hdd0
    #environment:
    #  - LABELS=M
    #  - SIZE=10

  ###########################
  # Chunkserver #2
  ###########################
  lizardfs-chunkserver-02:
    container_name: "lizardfs-chunkserver-02"
    hostname: lizardfs-chunkserver-02
    build: ./lizardfs-chunkserver
    #image: lizardfs/chunkserver
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.20.0.12"
    extra_hosts:
      - "mfsmaster:172.20.0.2"
    volumes:
      - /dev/log:/dev/log
    # - ./data/cs2_hdd0:/mnt/hdd0
    #environment:
    #  - LABELS=MB
    #  - SIZE=10

  ###########################
  # Chunkserver #3
  ###########################
  lizardfs-chunkserver-03:
    container_name: "lizardfs-chunkserver-03"
    hostname: lizardfs-chunkserver-03
    build: ./lizardfs-chunkserver
    #image: lizardfs/chunkserver
    depends_on:
      - lizardfs-master
    networks:
      lizardfs-net:
        ipv4_address: "172.20.0.13"
    extra_hosts:
      - "mfsmaster:172.20.0.2"
    volumes:
      - /dev/log:/dev/log
    # - ./data/cs3_hdd0:/mnt/hdd0
    #environment:
    #  - LABELS=MB
    #  - SIZE=10

###########################
# Network config
###########################
networks:
  lizardfs-net:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/16
